export interface EventDto {
    id: number;
    event_id: string;
    cal_id: number;
    summary: string;    
    date_start: string;
    date_end: string;
    sync_google: number;
    cal_summary: string;
    color_front: string;
    color_back: string;
    suiviDevisContrat: number;
    adresseDepart: string;
    nomAfficherSite: string;
    formule: string;
    crafterOverlap: boolean;
    isPast: boolean;
    equipe: string;
    groupe: string;
    ville: string;
    codePostal: string;
    nomEvenement: string;
    payant: boolean;
    dateEnvoi: Date;
    montant: number;
    feuilleDeRoute: string;
    heureConcerts: string;
    lieuRdv:string;
    repas: number;
    heureDebutConcert:string;
    heureBalance:string;
    heureRdvRepas:string;
    heureArrivee:string;
    heureDepart:string;
    heureRetour:string;
    equipeMusiciens:string;
    tempsChargementMinutes:number;
    infoSets:string;
    vehicule:number;  
    dateDepartCrafter:string;
    dateRetourCrafter:string;
    vehiculesPerso:string;
    location: string;
    train:string;
    adresseArrivee:string;
    distanceKm:number;
    dureeMinutes:number;
    dateArriveeHebergement:Date;
    adresseHebergement:string;
    contactHebergement:string;
    contactTechnique:string;
    contactAccueil:string;
    contactOrga:string;
    envoiKitCom: number;
    contactCom: string;
    lien:string;
    afficherSite:boolean;
    frequentation:number;
    precisions:string;
    transports:string;
    date_envoi: string;
    cachet: number;
    code_postal: string;
    description: string;
}